from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class GraphChatMessageIn(BaseModel):
    model_config = ConfigDict(extra="allow")

    role: str | None = Field(
        default="user",
        description="Message role. Typical values: user, assistant, system, tool.",
    )
    type: str | None = Field(
        default=None,
        description="Optional alias for role (supports LangChain-style payloads).",
    )
    content: str = Field(default="", description="Message content")
    tool_calls: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Tool calls for assistant messages.",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="Tool call id for tool messages.",
    )
    name: str | None = Field(
        default=None,
        description="Optional tool name for tool messages.",
    )


class GraphChatInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    messages: list[GraphChatMessageIn] = Field(
        default_factory=list,
        description="Conversation messages.",
    )
    thread_id: str | None = Field(
        default=None,
        description="Optional thread id used for conversation continuity.",
    )
    user_id: str | None = Field(
        default=None,
        description="Optional fallback identifier used when thread_id is not provided.",
    )


class GraphChatRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    input: GraphChatInput | None = Field(
        default=None,
        description="Optional wrapper format compatible with LangServe-like clients.",
    )
    messages: list[GraphChatMessageIn] | None = Field(
        default=None,
        description="Direct payload format messages.",
    )
    thread_id: str | None = Field(
        default=None,
        description="Direct payload thread id.",
    )
    user_id: str | None = Field(
        default=None,
        description="Direct payload fallback id.",
    )

    def normalized_input(self) -> GraphChatInput:
        if self.input is not None:
            return self.input
        return GraphChatInput(
            messages=self.messages or [],
            thread_id=self.thread_id,
            user_id=self.user_id,
        )


class GraphMessageOut(BaseModel):
    type: str = Field(description="Message type")
    content: str = Field(description="Message content")
    tool_calls: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Tool calls attached to message when present.",
    )


class GraphChatResponse(BaseModel):
    thread_id: str | None = Field(default=None, description="Thread id used for this run.")
    answer: str = Field(default="", description="Final assistant answer.")
    query_statement: str | None = Field(
        default=None,
        description="Latest query statement generated by the Graph workflow.",
    )
    df: list[Any] = Field(
        default_factory=list,
        description="Normalized data payload extracted from tool responses.",
    )
    graph_messages: list[GraphMessageOut] = Field(
        default_factory=list,
        description="Full graph message trail for the request.",
    )
